### ISSUE TITLE
UTF 8 encoding for csvs

### ISSUE THREAD

**Issue by jkerai1** [maaaaz/fgpoliciestocsv#10]
fgservicestocsv.py

Encoding is not set by default [](url
![Capture](https://user-images.githubusercontent.com/55988027/155727107-42274f55-495b-498f-9032-4e1822c787cf.PNG)
)

fixed by setting encoder to utf-8 in Line 155:

 with io.open(options.output_file, mode=fd_write_options,encoding="UTF-8") as fd_output:

fixed error for me

**Comment by maaaaz** [comment]
Hello and thank you for reporting this bug.
Which version of Python have you used ?

**Comment by maaaaz** [comment]
Fixed in https://github.com/maaaaz/fgpoliciestocsv/commit/b0a5197f04340cc62a8d665470f0916c03e90f3e
