### ISSUE TITLE
When i use fgaddressestocsv.py , it doesn´t work

### ISSUE THREAD

**Issue by giviney** [maaaaz/fgpoliciestocsv#16]
Good afternoon,
I find a useful script : fgaddressestocsv.py (Also fgpoliciestocsv.py , and it works ok). 

But for some reason, I'm getting errors. 

I've tried to search on Google for this error, But I'm afraid I have no idea how to apply them.

C:\PYTHON_POLICY_FORTIGATE\fgpoliciestocsv-master>python fgaddressestocsv.py -i prueba-address.cfg -n
Traceback (most recent call last):
  File "fgaddressestocsv.py", line 179, in <module>
    main()
  File "fgaddressestocsv.py", line 174, in main
    generate_csv(results, keys, options)
  File "fgaddressestocsv.py", line 151, in generate_csv
    spamwriter.writerow(output_line)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)

This is the Python version I'm using;
python --version
Python 2.7.18

Is it possible  , you give me some advice , please?

**Comment by maaaaz** [comment]
Hello, try using Python v3.

**Comment by giviney** [comment]
Thanks you a lot.

Yes , i tried with  python3 , and script ran successfull.
