### ISSUE TITLE
Help needed urgently with the file fgpoliciestocsv.py

### ISSUE THREAD

**Issue by vaibhavsomani** [maaaaz/fgpoliciestocsv#5]
Hi ,

I m trying to use your python script and getting the following error. Can you please help asap?

D:\Users\somaniv>csvparse.py -i rules1.cfg
Traceback (most recent call last):
  File "D:\Users\somaniv\csvparse.py", line 160, in <module>
    main(options, arguments)
  File "D:\Users\somaniv\csvparse.py", line 145, in main
    results, keys = parse(options.input_file)
  File "D:\Users\somaniv\csvparse.py", line 77, in parse
    if p_entering_policy_block.search(line):
TypeError: cannot use a string pattern on a bytes-like object

Please convert the txt file to cfg file. 

[rules1.txt](https://github.com/maaaaz/fgpoliciestocsv/files/2230356/rules1.txt)

**Comment by kaizen13** [comment]
Hi,

I am using the same script and getting the same traceback errors. I think the script was made for older FG firmware and maybe for python 2.7 but not sure.

It is immensely useful for fortigate firewall admins :)

**Comment by Redmage753** [comment]
> Hi,
> 
> I am using the same script and getting the same traceback errors. I think the script was made for older FG firmware and maybe for python 2.7 but not sure.
> 
> It is immensely useful for fortigate firewall admins if someone can fix it :) I am using python 3 and FG OS 5.6.

I was able to fix this issue by changing the input/read function "def parse(fd)" line from:
`	with open(fd,'rb') as fd_input:`
to 
`	with open(fd,'rt') as fd_input:`


Additionally, you'll need to change the output in function "def generate_csv" line from:
`        with open(fd,'wb') as fd_output:`
to
`        with open(fd,'wt') as fd_output:`


This changes the file read from "bytes" to "text".

**Comment by chrisben-college** [comment]
> I was able to fix this issue by changing the input/read function "def parse(fd)" line from:

This worked for me too - very useful thank you. Also using python3 and FortiOS 5.6.11

**Comment by maaaaz** [comment]
Thanks for your feedbacks, indeed I need to adapt the script to support Python 2 and 3. Not complex at all.

**Comment by maaaaz** [comment]
Hello there,
Should be fixed with the latest commit ensuring Python 2 and 3 compatibility.

Cheers.
